# apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
# kind: Kustomization
# metadata:
#   name: fleetman
#   namespace: flux-system
# spec:
#   interval: 1m0s
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   path: ./workloads/fleetman/dev
#   prune: true
#   validation: client
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: nginx
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/vipul71098/fleetman-flux.git