---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./workloads/fleetman/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: podinfo
  targetNamespace: default

